"""Add users table

Revision ID: 7396aaab462c
Revises: a1b2c3d4e5f6
Create Date: 2026-01-17 11:23:53.577752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7396aaab462c'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address (used for login)"),
    sa.Column('hashed_password', sa.String(length=255), nullable=True, comment='Bcrypt hashed password (null for OAuth users)'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Unique username for profile URLs'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment="User's full display name"),
    sa.Column('avatar_url', sa.Text(), nullable=True, comment="URL to user's avatar image"),
    sa.Column('bio', sa.Text(), nullable=True, comment='User biography'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the account is active'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Whether email has been verified'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Whether user has admin privileges'),
    sa.Column('auth_provider', sa.String(length=20), nullable=False, comment='Authentication provider (local, google, github)'),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True, comment='User ID from OAuth provider'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the user registered'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the user profile was last updated'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='When the user last logged in'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_provider_user_id'), 'users', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_provider_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
